import * as THREE from 'three';
import events from './events.json';
import cityData from './cities.json';
export async function createAtlas(host){
 let renderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});}catch{host.querySelector('.fallback').textContent='Atlas 3D indisponível neste dispositivo. A linha do tempo continua disponível abaixo.';return {set(){},focus(){},replay(){}};}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;host.append(renderer.domElement);host.dataset.engine='three';
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,100),group=new THREE.Group();scene.add(group,new THREE.HemisphereLight(0xffffff,0x7b6d52,2.5));const light=new THREE.DirectionalLight(0xfff5d6,3);light.position.set(4,6,8);scene.add(light);
 // === CINEMA LAYER: stars, armillary, dust ===
 const starGeo=new THREE.BufferGeometry();const starCount=1400;const starPositions=new Float32Array(starCount*3),starColors=new Float32Array(starCount*3),starSizes=new Float32Array(starCount);
 for(let i=0;i<starCount;i++){const r=THREE.MathUtils.randFloat(24,42),th=Math.random()*Math.PI*2,ph=Math.acos(2*Math.random()-1);starPositions[i*3]=r*Math.sin(ph)*Math.cos(th);starPositions[i*3+1]=r*Math.sin(ph)*Math.sin(th);starPositions[i*3+2]=r*Math.cos(ph);const warm=Math.random()<.28,g=THREE.MathUtils.randFloat(.7,1);starColors[i*3]=warm?g:g*.85;starColors[i*3+1]=g*.9;starColors[i*3+2]=warm?g*.7:g;starSizes[i]=THREE.MathUtils.randFloat(.4,1.9);}
 starGeo.setAttribute('position',new THREE.BufferAttribute(starPositions,3));starGeo.setAttribute('color',new THREE.BufferAttribute(starColors,3));starGeo.setAttribute('aSize',new THREE.BufferAttribute(starSizes,1));
 const starMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0}},vertexShader:'attribute float aSize; varying vec3 vColor; varying float vTwinkle; uniform float uTime; void main(){vColor=color;vTwinkle=0.72+0.28*sin(uTime*0.9+position.x*0.31+position.y*0.17);vec4 mv=modelViewMatrix*vec4(position,1.0);gl_Position=projectionMatrix*mv;gl_PointSize=aSize*(320.0/-mv.z)*vTwinkle;}',fragmentShader:'varying vec3 vColor; varying float vTwinkle; void main(){vec2 uv=gl_PointCoord-0.5;float d=length(uv);float core=smoothstep(0.5,0.0,d);float halo=smoothstep(0.5,0.15,d)*0.35;gl_FragColor=vec4(vColor*(core+halo),core*vTwinkle);}',vertexColors:true});
 const stars=new THREE.Points(starGeo,starMat);scene.add(stars);
 // Armillary sphere silhouette — 3 rings at different tilts
 const armGroup=new THREE.Group();
 const ringMat=new THREE.LineBasicMaterial({color:0xcda971,transparent:true,opacity:.14,blending:THREE.AdditiveBlending,depthWrite:false});
 for(let i=0;i<3;i++){const seg=128,pts=[];const R=6.2+i*.35;for(let j=0;j<=seg;j++){const a=(j/seg)*Math.PI*2;pts.push(new THREE.Vector3(R*Math.cos(a),R*Math.sin(a),0));}const g=new THREE.BufferGeometry().setFromPoints(pts);const ring=new THREE.Line(g,ringMat);ring.rotation.x=i*.7;ring.rotation.y=i*.4;armGroup.add(ring);}
 // Meridian
 const meridPts=[];for(let j=0;j<=64;j++){const a=(j/64)*Math.PI*2;meridPts.push(new THREE.Vector3(6.5*Math.sin(a),6.5*Math.cos(a),0));}const meridian=new THREE.Line(new THREE.BufferGeometry().setFromPoints(meridPts),ringMat.clone());meridian.material.opacity=.18;armGroup.add(meridian);
 scene.add(armGroup);
 // Dust motes drifting
 const dustCount=180,dustGeo=new THREE.BufferGeometry(),dustPos=new Float32Array(dustCount*3),dustSeed=new Float32Array(dustCount);
 for(let i=0;i<dustCount;i++){dustPos[i*3]=THREE.MathUtils.randFloat(-8,8);dustPos[i*3+1]=THREE.MathUtils.randFloat(-4,4);dustPos[i*3+2]=THREE.MathUtils.randFloat(-2,4);dustSeed[i]=Math.random()*100;}
 dustGeo.setAttribute('position',new THREE.BufferAttribute(dustPos,3));dustGeo.setAttribute('aSeed',new THREE.BufferAttribute(dustSeed,1));
 const dustMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0}},vertexShader:'attribute float aSeed; uniform float uTime; varying float vAlpha; void main(){vec3 p=position;p.x+=sin(uTime*0.18+aSeed)*0.6;p.y+=cos(uTime*0.13+aSeed*1.3)*0.4+sin(uTime*0.09+aSeed*.4)*.3;p.z+=cos(uTime*0.12+aSeed*.9)*.4;vec4 mv=modelViewMatrix*vec4(p,1.0);gl_Position=projectionMatrix*mv;gl_PointSize=(1.8+sin(uTime*.7+aSeed)*.5)*(240.0/-mv.z);vAlpha=0.22+0.14*sin(uTime*0.7+aSeed*2.0);}',fragmentShader:'varying float vAlpha; void main(){vec2 uv=gl_PointCoord-0.5;float d=length(uv);float core=smoothstep(0.5,0.0,d);gl_FragColor=vec4(0.95,0.85,0.62,core*vAlpha);}'});
 const dust=new THREE.Points(dustGeo,dustMat);scene.add(dust);
 // === END CINEMA LAYER ===
 let v=0,frame,tickHandle,started=0,angle=0,drag=false,lastX=0,reduced=false,selected=-1;const textures=[];let labels=[],routes=[];
 const clock=new THREE.Clock();let camBaseZ=8.4,camTargetZ=8.4,camTargetFov=36,camBaseFov=36,camTargetPan={x:0,y:0},camPan={x:0,y:0};
 // Per-marco camera profile: {z, fov, tilt}
 const marcoProfiles=[{z:8.2,fov:34,tilt:0.02},{z:8.6,fov:38,tilt:0.04},{z:8.4,fov:36,tilt:0.02},{z:7.9,fov:32,tilt:0.01},{z:8.5,fov:37,tilt:0.03},{z:8.3,fov:35,tilt:0.02},{z:8.1,fov:33,tilt:0.03},{z:7.7,fov:30,tilt:0},{z:8.5,fov:36,tilt:0.02},{z:8.3,fov:35,tilt:0.03}];
 const land=await fetch('./assets/land.json').then(r=>r.json()).catch(()=>null);
 const map=(dark=false)=>{const c=document.createElement('canvas');c.width=2048;c.height=1024;const x=c.getContext('2d');x.fillStyle=dark?'#142932':'#dbe2d4';x.fillRect(0,0,c.width,c.height);x.strokeStyle=dark?'#43605e':'#bdcbbb';x.lineWidth=1;for(let i=0;i<=24;i++){x.beginPath();x.moveTo(i*c.width/24,0);x.lineTo(i*c.width/24,c.height);x.stroke();}for(let i=0;i<=12;i++){x.beginPath();x.moveTo(0,i*c.height/12);x.lineTo(c.width,i*c.height/12);x.stroke();}x.fillStyle=dark?'#728676':'#778f74';for(const f of land?.features||[]){const polys=f.geometry.type==='MultiPolygon'?f.geometry.coordinates:[f.geometry.coordinates];for(const p of polys){x.beginPath();for(const ring of p){ring.forEach(([lon,lat],i)=>{const px=(lon+180)/360*c.width,py=(90-lat)/180*c.height;i?x.lineTo(px,py):x.moveTo(px,py);});x.closePath();}x.fill('evenodd');}}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;textures.push(t);return t;};
 const paleMap=map(),darkMap=map(true),loader=new THREE.TextureLoader();const photos=await Promise.all(['kilwa','cairo','timbuktu'].map(n=>loader.loadAsync('./assets/'+n+'.jpg').then(t=>{t.colorSpace=THREE.SRGBColorSpace;textures.push(t);return t;}).catch(()=>null)));
 const earth=await loader.loadAsync('./assets/earth-color.jpg');earth.colorSpace=THREE.SRGBColorSpace;earth.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());const normal=await loader.loadAsync('./assets/earth-normal.jpg'),specular=await loader.loadAsync('./assets/earth-specular.jpg');textures.push(earth,normal,specular);
 function mesh(geo,color,opts={}){const m=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color,roughness:.7,...opts}));group.add(m);return m;}
 function line(points,color,r=.012){return mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),80,r,8,false),color,{metalness:.1});}
 function sphere(lon,lat,r=2.04){const a=THREE.MathUtils.degToRad(lon),b=THREE.MathUtils.degToRad(lat);return new THREE.Vector3(r*Math.cos(b)*Math.cos(a),r*Math.sin(b),-r*Math.cos(b)*Math.sin(a));}
 const cities=[[-4,17],[31,30],[40,21],[40,-9],[41,-2],[-8,12]];
 function clear(){labels.forEach(l=>l.el.remove());labels=[];routes=[];group.traverse(o=>{o.geometry?.dispose();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());});group.clear();group.rotation.set(0,0,0);group.position.set(0,0,0);group.scale.setScalar(1);}
 function build(){clear();camera.position.set(0,0,8.4);camera.lookAt(0,0,0);const dark=v===1||v===6,color=dark?0xc9b67c:0x936338;
 if(v===0||v===1||v===3||v===4){
 const material=new THREE.MeshPhongMaterial({map:earth,normalMap:normal,normalScale:new THREE.Vector2(.23,.23),specularMap:specular,specular:new THREE.Color(0x273b4b),shininess:10,transparent:true,opacity:.92,depthWrite:false});
 material.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <dithering_fragment>','#include <dithering_fragment>\nfloat edgeFade = smoothstep(0.02, 0.48, abs(dot(normalize(vNormal), normalize(vViewPosition))));\ngl_FragColor.a *= edgeFade;');};
 const globe=new THREE.Mesh(new THREE.SphereGeometry(2,96,64),material);group.add(globe);
 const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(2.022,64,48),new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.BackSide,vertexShader:'varying vec3 n; varying vec3 eye; void main(){vec4 p=modelViewMatrix*vec4(position,1.0); n=normalize(normalMatrix*normal); eye=normalize(-p.xyz); gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 n; varying vec3 eye; void main(){float rim=pow(1.0-abs(dot(normalize(n),normalize(eye))),3.0);gl_FragColor=vec4(0.30,0.55,0.84,rim*0.32);}'}));group.add(atmosphere);
 const ids=selected<0?['timbuktu','cairo','kilwa']:events[selected].cities.filter(id=>cityData[id]);
 ids.forEach(id=>{const [lo,la,name]=cityData[id];const dot=mesh(new THREE.SphereGeometry(.022,12,10),0xfff3d5,{emissive:0x8f7550,emissiveIntensity:.6});dot.position.copy(sphere(lo,la,2.02));const el=document.createElement('button');el.className='city-tag';el.textContent=name;el.setAttribute('aria-label','Localizar '+name);el.onclick=()=>fly(lo,la,reduced);host.append(el);labels.push({el,point:sphere(lo,la,2.05)});});
 if(selected>=0)ids.forEach((id,i)=>{if(!i)return;const a=cityData[ids[i-1]],b=cityData[id],p=sphere(a[0],a[1],2.03),q=sphere(b[0],b[1],2.03),mid=p.clone().add(q).normalize().multiplyScalar(2.13);routes.push(line([p,mid,q],0xead7b2,.008));});group.rotation.y=-1.96;group.rotation.z=-.06;if(v===1){group.scale.setScalar(1.18);group.position.x=.3;}if(v===4){group.scale.setScalar(.95);group.rotation.z=-.2;}}
 else if(v===2){for(let i=0;i<3;i++){let arch=mesh(new THREE.TorusGeometry(.85,.15,14,80,Math.PI),0xccb79a);arch.position.set((i-1)*1.45,.15,-i*.4);for(const dx of [-.85,.85]){const p=mesh(new THREE.BoxGeometry(.28,1.45,.35),0xccb79a);p.position.set((i-1)*1.45+dx,-.56,-i*.4);}}group.rotation.y=-.4;group.rotation.x=.12;group.scale.setScalar(.95);}
 else if(v===5){for(let i=0;i<7;i++){const p=mesh(new THREE.BoxGeometry(2.8,.04,3.5),i%2?0xe4d3ad:0xfff3d6);p.rotation.y=(i-3)*.13;p.position.y=i*.09;}group.rotation.set(.8,.2,-.25);}
 else if(v===6){const points=Array.from({length:12},(_,i)=>new THREE.Vector3(Math.cos(i*2.4)*2.9,Math.sin(i*2.4)*1.15,Math.sin(i)*.8));points.forEach((p,i)=>{const n=mesh(new THREE.SphereGeometry(i===selected?.15:.09,24,16),i%3===0?0xc9b67c:0xa7c9bc);n.position.copy(p);if(i>0)line([points[Math.floor((i-1)/2)],p],0x648c88,.012);});group.position.y=-.35;}
 else if(v===7){const geo=new THREE.PlaneGeometry(12,7,140,80),p=geo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);p.setZ(i,Math.sin(x*1.2+y)*.17+Math.cos(y*2-x*.6)*.12);}geo.computeVertexNormals();const ocean=mesh(geo,0x556b7d,{metalness:.15,roughness:.55,side:THREE.DoubleSide,transparent:true,opacity:.8});ocean.rotation.x=-1.1;group.rotation.z=-.1;group.position.set(.5,-.5,0);for(let j=0;j<3;j++)line([new THREE.Vector3(-3,-.3+j*.5,.8),new THREE.Vector3(0,.4+j*.4,1.15),new THREE.Vector3(3,.8+j*.3,.7)],0xd8d4c7,.016);}
 else if(v===8){const p=mesh(new THREE.PlaneGeometry(4.8,3.2),0xffffff,{map:photos[Math.max(0,selected)%3],side:THREE.DoubleSide});p.rotation.y=-.12;camera.position.z=8;group.position.y=.15;}
 else{const colors=[0x964833,0x365a60,0x9a823a];for(let j=0;j<3;j++){const pts=Array.from({length:8},(_,i)=>new THREE.Vector3((i-3.5)*.8,Math.sin(i*.8+j)*.48+(j-1)*1.15,Math.cos(i*.5+j)*.6));line(pts,colors[j],.065);pts.forEach((p,i)=>{const dot=mesh(new THREE.SphereGeometry(i===selected%8?.16:.095,20,12),colors[j]);dot.position.copy(p);});}group.rotation.set(.1,-.35,.38);}
 }
 function size(){const r=host.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();render();}
 function updateCinema(){const t=clock.getElapsedTime();starMat.uniforms.uTime.value=t;dustMat.uniforms.uTime.value=t;armGroup.rotation.y=t*0.014;armGroup.rotation.z=Math.sin(t*0.11)*0.02;stars.rotation.y=t*0.0035;stars.rotation.x=t*0.0012;
  // Camera breathe + smooth pan easing (parallax)
  const breatheZ=Math.sin(t*0.42)*0.055;const targetZ=camTargetZ+breatheZ;camera.position.z+=(targetZ-camera.position.z)*0.06;
  camPan.x+=(camTargetPan.x-camPan.x)*0.05;camPan.y+=(camTargetPan.y-camPan.y)*0.05;camera.position.x=camPan.x;camera.position.y=camPan.y;
  const fovDelta=(camTargetFov-camera.fov);if(Math.abs(fovDelta)>0.01){camera.fov+=fovDelta*0.06;camera.updateProjectionMatrix();}
  camera.lookAt(0,camPan.y*0.15,0);}
 function tick(){updateCinema();render();tickHandle=requestAnimationFrame(tick);}
 function render(){renderer.render(scene,camera);group.updateMatrixWorld();const rect=host.getBoundingClientRect(),placed=[];labels.forEach(l=>{const world=l.point.clone().applyMatrix4(group.matrixWorld),p=world.clone().project(camera),x=(p.x*.5+.5)*rect.width,y=(-p.y*.5+.5)*rect.height;let visible=world.z>group.position.z&&Math.abs(p.x)<.8&&Math.abs(p.y)<.9;if(placed.some(pos=>Math.abs(pos.x-x)<120&&Math.abs(pos.y-y)<44))visible=false;l.el.hidden=!visible;if(visible){placed.push({x,y});l.el.style.transform=`translate(${x}px,${y}px) translate(10px,-50%)`;}});}
 function fly(lon,lat,r=false){cancelAnimationFrame(frame);const from=group.rotation.clone(),targetX=THREE.MathUtils.degToRad(lat),targetY=-Math.PI/2-THREE.MathUtils.degToRad(lon);const start=performance.now();function tick(now){const t=r?1:Math.min(1,(now-start)/850),ease=1-Math.pow(1-t,3);group.rotation.set(THREE.MathUtils.lerp(from.x,targetX,ease),THREE.MathUtils.lerp(from.y,targetY,ease),THREE.MathUtils.lerp(from.z,0,ease));routes.forEach(route=>route.geometry.setDrawRange(0,Math.floor(route.geometry.index.count*ease/3)*3));host.dataset.travel=t<1?'moving':'complete';render();if(t<1)frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);}
 function replay(r=false){reduced=r;cancelAnimationFrame(frame);started=performance.now();const target=group.rotation.y;const base=group.rotation.clone();function tick(now){const t=reduced?1:Math.min(1,(now-started)/400),ease=1-Math.pow(1-t,4);group.rotation.y=target+(1-ease)*.2;group.rotation.x=base.x+(1-ease)*.06;render();if(t<1)frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);}
 renderer.domElement.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;renderer.domElement.setPointerCapture(e.pointerId);cancelAnimationFrame(frame);});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;angle=(e.clientX-lastX)*.004;lastX=e.clientX;group.rotation.y+=angle;});renderer.domElement.addEventListener('pointerup',()=>drag=false);renderer.domElement.addEventListener('pointercancel',()=>drag=false);
 // Pointer parallax on host area
 host.addEventListener('pointermove',e=>{if(reduced)return;const r=host.getBoundingClientRect();const nx=((e.clientX-r.left)/r.width-0.5)*2,ny=((e.clientY-r.top)/r.height-0.5)*2;camTargetPan.x=nx*0.35;camTargetPan.y=-ny*0.22;});
 host.addEventListener('pointerleave',()=>{camTargetPan.x=0;camTargetPan.y=0;});
 function applyMarcoCamera(e){if(e<0){camTargetZ=camBaseZ;camTargetFov=camBaseFov;return;}const p=marcoProfiles[e]||marcoProfiles[0];camTargetZ=p.z;camTargetFov=p.fov;}
 new ResizeObserver(size).observe(host);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(frame);cancelAnimationFrame(tickHandle);host.dataset.engine='unavailable';host.querySelector('.fallback').textContent='Visualização pausada pelo dispositivo. Recarregue para recuperar o 3D.';});
 tick();
 return {set(n,r,e){v=n;selected=e;applyMarcoCamera(e);build();size();replay(r);},focus(e,r){const previous=group.rotation.clone();selected=e;reduced=r;applyMarcoCamera(e);build();size();if([0,1,3,4].includes(v)){group.rotation.copy(previous);const ids=events[e].cities.filter(id=>cityData[id]);const anchor=cityData[ids[e===7?2:0]]||cityData[ids[0]];fly(anchor[0],anchor[1],r);}else replay(r);},replay,camera,scene,renderer};
}
